# Generated by Django 6.0.5 on 2026-05-08 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(help_text='Nomor surat resmi (contoh: 001/SM/IV/2026)', max_length=100, unique=True, verbose_name='Nomor Surat')),
                ('pengirim', models.CharField(help_text='Nama instansi atau organisasi pengirim', max_length=200, verbose_name='Pengirim')),
                ('perihal', models.TextField(help_text='Perihal atau subjek surat', verbose_name='Perihal')),
                ('tanggal_surat', models.DateField(help_text='Tanggal yang tertera pada surat', verbose_name='Tanggal Surat')),
                ('tanggal_diterima', models.DateTimeField(auto_now_add=True, help_text='Tanggal surat diterima di sistem', verbose_name='Tanggal Diterima')),
                ('file_surat', models.FileField(blank=True, help_text='Upload file surat (PDF, DOCX, atau gambar)', null=True, upload_to='surat_masuk/', verbose_name='File Surat')),
                ('status', models.CharField(choices=[('baru', 'Baru'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='baru', help_text='Status pemrosesan surat', max_length=20, verbose_name='Status')),
                ('catatan', models.TextField(blank=True, help_text='Catatan tambahan terkait surat', null=True, verbose_name='Catatan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('diupdate_pada', models.DateTimeField(auto_now=True, verbose_name='Diupdate Pada')),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_masuk_dibuat', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh')),
                ('ditugaskan_ke', models.ForeignKey(blank=True, help_text='Staff yang ditugaskan untuk menangani surat ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_masuk_ditugaskan', to=settings.AUTH_USER_MODEL, verbose_name='Ditugaskan Ke')),
            ],
            options={
                'verbose_name': 'Surat Masuk',
                'verbose_name_plural': 'Surat Masuk',
                'ordering': ['-tanggal_diterima'],
                'indexes': [models.Index(fields=['nomor_surat'], name='accounts_su_nomor_s_2d3979_idx'), models.Index(fields=['status'], name='accounts_su_status_22c8a6_idx'), models.Index(fields=['-tanggal_diterima'], name='accounts_su_tanggal_9f6be0_idx')],
            },
        ),
    ]
