# Generated by Django 6.0.5 on 2026-05-08 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suratmasuk',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='suratmasuk',
            name='accounts_su_nomor_s_2d3979_idx',
        ),
        migrations.RemoveIndex(
            model_name='suratmasuk',
            name='accounts_su_status_22c8a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='suratmasuk',
            name='accounts_su_tanggal_9f6be0_idx',
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='dibuat_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_dibuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='ditugaskan_ke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_tugas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='diupdate_pada',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='nomor_surat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='pengirim',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='perihal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Diproses', 'Diproses'), ('Selesai', 'Selesai')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='suratmasuk',
            name='tanggal_surat',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='suratmasuk',
            name='catatan',
        ),
        migrations.RemoveField(
            model_name='suratmasuk',
            name='file_surat',
        ),
        migrations.RemoveField(
            model_name='suratmasuk',
            name='tanggal_diterima',
        ),
    ]
