# Generated by Django 6.0.5 on 2026-05-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_suratkeluar'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisi',
            name='prioritas',
            field=models.CharField(choices=[('biasa', 'Biasa'), ('segera', 'Segera')], default='biasa', max_length=20, verbose_name='Prioritas'),
        ),
        migrations.AddField(
            model_name='disposisi',
            name='tenggat_waktu',
            field=models.DateField(blank=True, null=True, verbose_name='Tenggat Waktu'),
        ),
        migrations.AddField(
            model_name='suratmasuk',
            name='prioritas',
            field=models.CharField(choices=[('biasa', 'Biasa'), ('segera', 'Segera')], default='biasa', max_length=20, verbose_name='Prioritas'),
        ),
        migrations.AddField(
            model_name='suratmasuk',
            name='tenggat_waktu',
            field=models.DateField(blank=True, null=True, verbose_name='Tenggat Waktu'),
        ),
    ]
