# Generated by Django 6.0.5 on 2026-05-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_disposisi_prioritas_disposisi_tenggat_waktu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisi',
            name='catatan_penyelesaian',
            field=models.TextField(blank=True, help_text='Catatan dari staff saat menyelesaikan disposisi', null=True, verbose_name='Catatan Penyelesaian'),
        ),
        migrations.AddField(
            model_name='disposisi',
            name='file_bukti',
            field=models.FileField(blank=True, help_text='Bukti file kerja dari staff', null=True, upload_to='bukti_disposisi/', verbose_name='File Bukti Penyelesaian'),
        ),
    ]
