# Generated by Django 6.0.5 on 2026-05-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_disposisi_catatan_penyelesaian_disposisi_file_bukti'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisi',
            name='tanggal_dibaca',
            field=models.DateTimeField(blank=True, help_text='Timestamp saat staff pertama kali membuka surat', null=True, verbose_name='Tanggal Dibaca'),
        ),
        migrations.AlterField(
            model_name='disposisi',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('dibaca', 'Dibaca'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='baru', max_length=20, verbose_name='Status'),
        ),
    ]
