# Generated by Django 6.0.5 on 2026-05-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_disposisi_tanggal_dibaca_alter_disposisi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='jabatan',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instansi'),
        ),
    ]
