# Generated by Django 6.0.5 on 2026-05-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_userprofile_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratkeluar',
            name='departemen',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('GA', 'General Affairs'), ('FIN', 'Finance')], default='GA', max_length=10, verbose_name='Departemen'),
        ),
        migrations.AddField(
            model_name='suratkeluar',
            name='jenis_surat',
            field=models.CharField(choices=[('SK', 'Surat Keputusan'), ('SE', 'Surat Edaran'), ('SP', 'Surat Pemberitahuan'), ('SU', 'Surat Undangan')], default='SU', max_length=10, verbose_name='Jenis Surat'),
        ),
    ]
