# Generated by Django 6.0.5 on 2026-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_suratkeluar_departemen_suratkeluar_jenis_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratkeluar',
            name='file_pdf_final',
            field=models.FileField(blank=True, help_text='File PDF hasil generate otomatis', null=True, upload_to='surat_keluar_pdf/', verbose_name='File PDF Final'),
        ),
        migrations.AddField(
            model_name='suratkeluar',
            name='isi_surat',
            field=models.TextField(blank=True, help_text='Isi / body teks surat', null=True, verbose_name='Isi Surat'),
        ),
        migrations.AlterField(
            model_name='suratkeluar',
            name='file_draf',
            field=models.FileField(blank=True, help_text='Upload file draf lampiran (opsional jika generate PDF)', null=True, upload_to='surat_keluar_draf/', verbose_name='File Draf'),
        ),
    ]
