# Generated by Django 6.0.5 on 2026-05-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_suratkeluar_file_pdf_final_suratkeluar_isi_surat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratkeluar',
            name='catatan_revisi',
            field=models.TextField(blank=True, help_text='Catatan dari Admin jika surat dikembalikan untuk direvisi', null=True, verbose_name='Catatan Revisi'),
        ),
        migrations.AlterField(
            model_name='suratkeluar',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('diajukan', 'Diajukan'), ('revisi', 'Revisi'), ('disetujui', 'Disetujui')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
