# Generated by Django 6.0.5 on 2026-05-29 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_suratkeluar_catatan_revisi_alter_suratkeluar_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi',
            name='penerima_disposisi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposisi_diterima', to=settings.AUTH_USER_MODEL, verbose_name='Penerima Disposisi'),
        ),
        migrations.AlterField(
            model_name='suratkeluar',
            name='pembuat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_surat_keluar', to=settings.AUTH_USER_MODEL, verbose_name='Pembuat'),
        ),
    ]
