# Generated by Django 6.0.5 on 2026-06-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_disposisi_penerima_disposisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratkeluar',
            name='jenis_surat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Klasifikasi'),
        ),
    ]
